UI Pages and themes
ESP-Group-16/food-waste-program pull request #1
Opened 2023-02-15 12:18 UTC by ange-02

Contains initial UI design for main pantry screen, user settings, pantry users dialog and add ingredient dialog. Also, colors and themes.

2023-02-17 10:22 UTC, penguoir requested changes

2023-02-17 10:22 UTC, penguoir commented on app/src/main/res/values/themes.xml
> +    <style name="Theme.MyApplication" parent="Theme.MaterialComponents.DayNight.NoActionBar">
This doesn't look right

2023-02-17 10:22 UTC, penguoir commented on app/src/main/res/layout/activity_profile.xml
> +        android:textStyle="bold"
Can we extract this into components? e.g. a Title component rather than textSize and textStyle?

2023-02-17 10:22 UTC, penguoir commented on app/src/main/res/layout/activity_profile.xml
> +                android:textColor="@color/black"
Minor, but https://anthonyhobday.com/sideprojects/saferules/

2023-02-17 10:22 UTC, penguoir commented on app/src/main/res/layout/activity_profile.xml
> +        android:layout_marginTop="20sp"/>
Again, extract to reusable component.

2023-02-17 10:22 UTC, penguoir commented on app/src/main/res/layout/dialog_add_ingredient.xml
> +        android:id="@+id/add"
Aren't these ids global? I'd think we need more specific names

2023-02-17 10:22 UTC, penguoir commented on app/src/main/res/values/themes.xml
> +    <style name="Theme.MyApplication" parent="Theme.MaterialComponents.DayNight.NoActionBar">
In fact, it breaks the app for me

2023-02-17 10:22 UTC, penguoir commented on app/src/main/res/values/themes.xml
> +    <style name="Theme.MyApplication.PopupOverlay" parent="ThemeOverlay.AppCompat.Light" />
Change MyApplication -> ESPProject

2023-02-17 10:43 UTC, ange-02 commented on app/src/main/res/layout/dialog_add_ingredient.xml
> +        android:id="@+id/add"
Why has this become a textview?
Also, will change to dialogAddIngredientButton

2023-02-17 10:48 UTC, penguoir commented
Just to be clear, I'm waiting for a commit on this branch that addresses the comments.

2023-02-19 19:50 UTC, penguoir commented
Not all issues are fixed in the latest commit. The theme is still called MyApplication rather than ESPProject.

2023-03-03 18:00 UTC, merged