Espg16-129 create model classes for data ryan
ESP-Group-16/food-waste-program pull request #2
Opened 2023-02-16 16:49 UTC by ryandavidsutton

Model classes completed - some little changes need to be made for TODO's in the model classes but from communication with emi the current version is sufficient to be worked ontop of

2023-02-17 10:29 UTC, penguoir requested changes

2023-02-17 10:29 UTC, penguoir commented on app/src/main/java/com/example/espproject/Food.java
> +public class Food { // TODO: check access modifiers.
What does this TODO mean?

2023-02-17 10:29 UTC, penguoir commented on app/src/main/java/com/example/espproject/Food.java
> +    private ArrayList<String> dietaryInfo;
I don't think this type is correct. Is one dietaryInfo a string?

2023-02-17 10:29 UTC, penguoir commented on app/src/main/java/com/example/espproject/Food.java
> +    private ArrayList<String> dietaryInfo;
Maybe it's food? Allergies?

2023-02-17 10:29 UTC, penguoir commented on app/src/main/java/com/example/espproject/Food.java
> +    private Dictionary<String, Integer> nutritional_info;
should be `nutritionalInfo`, why is this a String -> Integer map?

2023-02-17 10:29 UTC, penguoir commented on app/src/main/java/com/example/espproject/Pantry.java
> +    private int pantryId; // Changed from id to pantryId (per UML diagram)
No need to stick to the UML diagram. `id` is more concise and prevents code stutter:

2023-02-17 10:29 UTC, penguoir commented on app/src/main/java/com/example/espproject/Pantry.java
> +    // New added attributes
What does this mean?

2023-02-17 10:29 UTC, penguoir commented on app/src/main/java/com/example/espproject/Pantry.java
> +    private ArrayList<User> userArrayList;
What does `userArrayList` mean?

2023-02-17 10:29 UTC, penguoir commented on app/src/main/java/com/example/espproject/Pantry.java
> +    // New Attribute Getters and Setters
What are "New attribute"s ?

2023-02-17 10:29 UTC, penguoir commented on app/src/main/java/com/example/espproject/Recipe.java
> +    private ArrayList<String> ingredients;
Array of Strings?

2023-02-17 10:29 UTC, penguoir commented on app/src/main/java/com/example/espproject/Recipe.java
> +    private ArrayList<String> dietaryInfo;
Array of strings?

2023-02-17 10:30 UTC, penguoir commented
I have more comments, but I think you get the gist: The UML diagram was just a building block, from here we should choose the best types, especially if this is the base of all other business logic code.

2023-02-17 12:13 UTC, ryandavidsutton commented on app/src/main/java/com/example/espproject/Food.java
> +    private ArrayList<String> dietaryInfo;
@ekc30 Any input on this?

2023-02-17 12:18 UTC, ryandavidsutton commented on app/src/main/java/com/example/espproject/Food.java
> +public class Food { // TODO: check access modifiers.
Access modifiers are the 'private', 'protected', 'public' - I was unsure whether they were correct for each variable so I wrote that to help the next developer check. But:

Talked to emi about it and she said that all the access modifiers are ok so I'll edit the TODO line out.

2023-02-17 12:20 UTC, ryandavidsutton commented on app/src/main/java/com/example/espproject/Food.java
> +    private Dictionary<String, Integer> nutritional_info;
Changed the name but again I am not sure on the actual content of this variable.
@ekc30 ?

2023-02-17 12:20 UTC, ryandavidsutton commented on app/src/main/java/com/example/espproject/Food.java
> +    private ArrayList<String> dietaryInfo;
Or @ange-02?

2023-02-17 12:20 UTC, ryandavidsutton commented on app/src/main/java/com/example/espproject/Food.java
> +    private Dictionary<String, Integer> nutritional_info;
Or @ange-02?

2023-02-17 12:21 UTC, ryandavidsutton commented on app/src/main/java/com/example/espproject/Pantry.java
> +    private int pantryId; // Changed from id to pantryId (per UML diagram)
Sure changed it back.

2023-02-17 12:23 UTC, ryandavidsutton commented on app/src/main/java/com/example/espproject/Pantry.java
> +    private ArrayList<User> userArrayList;
I changed it to userList <- I refactored all instances of List to ArrayList when updating data types (I am not sure what this variable is used for though).

2023-02-17 12:23 UTC, ryandavidsutton commented on app/src/main/java/com/example/espproject/Pantry.java
> +    // New added attributes
Some of the files had previous code in them - I marked all the things I added as in the UML diagram under comments like those.

2023-02-17 12:25 UTC, ryandavidsutton commented on app/src/main/java/com/example/espproject/Pantry.java
> +    // New Attribute Getters and Setters
As mentioned on the ticket above. 'New Attributes' are ones that were not already existing in the java files when I got access to them. (Some variables already were implemented with getters and setters before I edited the files).

2023-02-17 12:25 UTC, ryandavidsutton commented on app/src/main/java/com/example/espproject/Recipe.java
> +    private ArrayList<String> ingredients;
@ekc30 @ange-02 would be the best people to ask for this - I'm not sure.

2023-02-17 12:26 UTC, ryandavidsutton commented on app/src/main/java/com/example/espproject/Recipe.java
> +    private ArrayList<String> dietaryInfo;
Again @ekc30 @ange-02, do you have any input?

2023-02-17 12:32 UTC, ange-02 commented on app/src/main/java/com/example/espproject/Food.java
> +    private Dictionary<String, Integer> nutritional_info;
Imo, nutritional info can be a json of the form 

{
    sugars:  int,
    carbs: int
...
}
Doing it as a list could also work if we standardise what each index in the list refers to, but it's a bit hacky and hard to expand.

2023-02-17 12:34 UTC, ange-02 commented on app/src/main/java/com/example/espproject/Food.java
> +    private Dictionary<String, Integer> nutritional_info;
Also, does dietary info refer to what allergies it could trigger?

2023-02-17 12:53 UTC, ange-02 commented on app/src/main/java/com/example/espproject/Recipe.java
> +    private ArrayList<String> ingredients;
Imo, they both can be Arrays of strings, because these are really only used to populate the UI. 
When retrieving a recipe's ingredients from the database, we can store them in a Java array and then place them in a RecyclerView. We don't need anything fancy like a dictionary as that would complicate things unnecessarily. Also, I presume the strings would be stored as "100g chicken", right?
As for dietary info, same points as above, not 100% clear what it is.

2023-02-20 22:06 UTC, ryandavidsutton commented on app/src/main/java/com/example/espproject/Food.java
> +    private Dictionary<String, Integer> nutritional_info;
> Imo, nutritional info can be a json of the form
> 
> { sugars: int, carbs: int ... } Doing it as a list could also work if we standardise what each index in the list refers to, but it's a bit hacky and hard to expand.

Changed datatype to json.

2023-02-20 22:22 UTC, ryandavidsutton commented on app/src/main/java/com/example/espproject/Food.java
> +    private Dictionary<String, Integer> nutritional_info;
> > Imo, nutritional info can be a json of the form
> > { sugars: int, carbs: int ... } Doing it as a list could also work if we standardise what each index in the list refers to, but it's a bit hacky and hard to expand.
> 
> Changed datatype to json.

Ok nvm this is kinda complicated for some reason

2023-02-20 22:28 UTC, ryandavidsutton commented on app/src/main/java/com/example/espproject/Food.java
> +    private Dictionary<String, Integer> nutritional_info;
Apparantely you need to download a .jar file then add it to the classpath/ use maven (either of which I'm not sure how to do for this github file) and then do something with a file called pom.xml?

I'm lost. But here's the resources I found:
https://www.geeksforgeeks.org/working-with-json-data-in-java/
https://www.tutorialspoint.com/json_simple/json_simple_environment.htm

2023-02-21 08:35 UTC, penguoir commented on app/src/main/java/com/example/espproject/Food.java
> +    private Dictionary<String, Integer> nutritional_info;
JSON isn't a type, it's a way of saving data. I agree with Andrew's comment, but we could use a Java Hashmap.

2023-02-24 13:55 UTC, ryandavidsutton commented on app/src/main/java/com/example/espproject/Food.java
> +    private Dictionary<String, Integer> nutritional_info;
Finished changes

2023-02-24 13:55 UTC, ryandavidsutton commented
@penguoir Should be able to merge this now no?

2023-02-26 19:08 UTC, closed without merging